### ISSUE TITLE
Add bottom navigation bar

### ISSUE THREAD

**Issue by Harsh-Vipin** [Harsh-Vipin/cosmoscribe#10]
Add a bottom navigation bar with four pages

**Comment by gantanikhilraj** [comment]
@Harsh-Vipin Can you give me some more details on this issue ?

**Comment by Harsh-Vipin** [comment]
@gantanikhilraj 

-  create a widget called main screen (create main_screen.dart)
- add a bottom nav bar with four children 
- each child can be a scaffold with name page1,page2 etc

**Comment by hetpatel4381** [comment]
@Harsh-Vipin can you assign me this task i can do it.

**Comment by gantanikhilraj** [comment]
Hi @Harsh-Vipin , this issue is already assigned, please look for another issues.

**Comment by Harsh-Vipin** [comment]
@hetpatel4381  you could work on issue  #17 if you like :)

**Comment by gantanikhilraj** [comment]
@hetpatel4381 , I have already started to work on this. Will create a PR soon.

**Comment by gantanikhilraj** [comment]
@Harsh-Vipin , Created a PR. Please let me know if you need any changes.
