### ISSUE TITLE
Fix issues in splash screen and enhance the UI

### ISSUE THREAD

**Issue by Yaswanth-Mitta** [Harsh-Vipin/cosmoscribe#5]
Hey @Harsh-Vipin is there anthing i can contribute ?

**Comment by Harsh-Vipin** [comment]
Sure you can work on the splash Screen

**Comment by Harsh-Vipin** [comment]
@Yaswanth-Mitta Hey are you working on it? do tell me if you are facing any issues

**Comment by Yaswanth-Mitta** [comment]
@Harsh-Vipin  yeah i was working on a flutter project which is using different flutter version so that is the root cause of the delay. yeah what kind of improvements do i need to make can you eleborate that and do i need to another custom splash screen ?

**Comment by Harsh-Vipin** [comment]
@Yaswanth-Mitta

-  in the same display fix the render issue
- add loading functionality 
- display the screen for 3 seconds and move to the Home Screen

**Comment by Yaswanth-Mitta** [comment]
@Harsh-Vipin  So I need to show progress indicator until the data  and the image is loaded after 3 seconds of data being loaded then i need to navigate to another screen right?
