### ISSUE TITLE
Integration of NASA NEO API with Date Pickers and Home Screen

### ISSUE THREAD

**Issue by Harsh-Vipin** [Harsh-Vipin/cosmoscribe#6]
- integrate the api https://api.nasa.gov/neo/rest/v1/feed?start_date=2015-09-07&end_date=2015-09-08&api_key=DEMO_KEY 
- Create a Home Screen and add date pickers to give input to the api 

- Refer https://api.nasa.gov for further details.

**Comment by Priyammm05** [comment]
Can you assign it to me

**Comment by Harsh-Vipin** [comment]
@Priyammm05  it is done partially, you could complete the rest

**Comment by Priyammm05** [comment]
Does this require to create a api key too ?

**Comment by Harsh-Vipin** [comment]
@Priyammm05  Not necessary , you can  the demo key as per the documentation. Do star the repo if you like it :)

**Comment by Priyammm05** [comment]
Can you please describe what you need in home_page UI like it should just call the api based on the dates or something more

**Comment by Harsh-Vipin** [comment]
@Priyammm05  date pickers to input the date and the result can be shown as a list . you could make any other changes to enhance the ui.

**Comment by Priyammm05** [comment]
Do you want all the results that the api is giving so just few of them ?

**Comment by Harsh-Vipin** [comment]
@Priyammm05  what about pagination? wouldn't that be better

**Comment by Priyammm05** [comment]
This api gives the information about the celestial bodies that can pass very nearly to the earth

**Comment by Harsh-Vipin** [comment]
It gives a list of near earth objects , you can show as list with the name and some other necessary information which you find necessary.

**Comment by Priyammm05** [comment]
![image](https://github.com/Harsh-Vipin/cosmoscribe/assets/80326453/ccd7efc7-6a39-41bc-8e66-8470bdab99b6)
 
Anything more to be done ?

**Comment by Harsh-Vipin** [comment]
@Priyammm05 great work 😁. You can create a pr
